### ISSUE TITLE
Version lookup of events

### ISSUE THREAD

**Issue by eByte23** [domagojk/beenion#4]
https://github.com/domagojk/beenion/blob/67214ed53bfad1f794ec9a06644c221efeb94bad/infrastructure/databases/eventstore/dynamoDbEventStore.ts#L28

Hi,

Thanks for the blog post was a good, using some of your design to influence my c# eventsoucing on lambda.

Just noticed the above property and the lookup is >= version.

I can't really see exactly where use this in your code base but i'd assume you be doing <= version? as you'd want to pin the aggregate at that version correct?
Just going of how I have previously done things.

Cheers,
Elijah

**Comment by domagojk** [comment]
@eByte23 hello, I'm glad you liked the blog.

You can see [here](https://github.com/domagojk/beenion/blob/master/application/user.ts#L13) how I'm using it.

Since the version is not defined, it will fall-back to 0, which means it will query everything for that userId from version 0. In other words, it will get all "commits" (batches of events) for that user, which is what I want.

If I would've used <= then I wouldn't get any new events, but only the ones which are defined before a certain point. I guess that is what you are saying (pinning the aggregate to a certain version), but I don't see how that would be useful here?

Note that this version will increment every time a new item is saved in Dynamo. So it's not a "logical" version which impacts the format of the model (that is another kind of version, not related to this). A version saved in DynamoDb is used only for optimistic locking (used [here](https://github.com/domagojk/beenion/blob/master/application/user.ts#L13)) so I can ensure nobody will change anything for that user while the command was executing.

Hope that makes sense?

**Comment by eByte23** [comment]
Thanks for the reply.
I did notice that after reviewing my implementation.
I have optional pinning on the version. 

Reasoning behind was that on a previous system I made we had a certain set of aggregates that x amount of versions when we wanted to pin to a version and generate read models at that version.

Anyway, understand exactly the implementation now just didn't read thoroughly enough.
Thanks!
